slug = "lost-doggo"
title = "Lost Doggo"
author = "Yufa"
value = 50
description = """My dog got out while chasing a squirrel, and now I can't even find a picture of him to put up! Can you figure out his name for the Missing Dog posters?"""
tags = [ "file" ]
files = [ "doggo.jpg" ]
flag = "flag{scooby_snoopy_doo}"
enabled = true